export const teamLogos: Record<string, string> = {
  'ARI': 'https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg',
  'ATL': 'https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg',
  'BAL': 'https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg',
  'BUF': 'https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg',
  'CAR': 'https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg',
  'CHI': 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg',
  'CIN': 'https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg',
  'CLE': 'https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg',
  'DAL': 'https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg',
  'DEN': 'https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg',
  'DET': 'https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg',
  'GB':  'https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg',
  'HOU': 'https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg',
  'IND': 'https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg',
  'JAX': 'https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg',
  'KC':  'https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg',
  'LV':  'https://upload.wikimedia.org/wikipedia/en/5/5c/Las_Vegas_Raiders_logo.svg',
  'LAC': 'https://upload.wikimedia.org/wikipedia/en/7/72/Los_Angeles_Chargers_logo.svg',
  'LAR': 'https://upload.wikimedia.org/wikipedia/en/8/8a/Los_Angeles_Rams_logo.svg',
  'MIA': 'https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg',
  'MIN': 'https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg',
  'NE':  'https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg',
  'NO':  'https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg',
  'NYG': 'https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg',
  'NYJ': 'https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo_2019.svg',
  'PHI': 'https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg',
  'PIT': 'https://upload.wikimedia.org/wikipedia/en/d/de/Pittsburgh_Steelers_logo.svg',
  'SEA': 'https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg',
  'SF':  'https://upload.wikimedia.org/wikipedia/en/3/3a/San_Francisco_49ers_logo.svg',
  'TB':  'https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg',
  'TEN': 'https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg',
  'WAS': 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Washington_Commanders_logo.svg'
}
export const playerHeadshots: Record<string, string> = {
  'patrick mahomes': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Patrick_Mahomes_2023.jpg/128px-Patrick_Mahomes_2023.jpg',
  'justin jefferson': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Justin_Jefferson_2022.jpg/128px-Justin_Jefferson_2022.jpg',
  'christian mccaffrey': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Christian_McCaffrey_2019.jpg/128px-Christian_McCaffrey_2019.jpg',
  'puka nacua': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Puka_Nacua_2023.jpg/128px-Puka_Nacua_2023.jpg',
  'travis kelce': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Travis_Kelce_Super_Bowl_LVII_Victory_Parade_%28cropped%29.jpg/128px-Travis_Kelce_Super_Bowl_LVII_Victory_Parade_%28cropped%29.jpg',
  'justin tucker': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Justin_Tucker_2018_%28cropped%29.jpg/128px-Justin_Tucker_2018_%28cropped%29.jpg'
}
